theme: jekyll-theme-minimal
title: API Client Boilerplate .NET
description: A template repository for .NET API clients projects.
logo: https://raw.githubusercontent.com/guibranco/apiclient-boilerplate-dotnet/main/logo.png
show_downloads: true
